version: "3.8"

networks:
    default:
        name: proxynet

services:
    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        env_file:
            - ./.env.mysql
        volumes:
            - mysqldata:/var/lib/mysql

    backendbase: &backendbase
        build:
            context: .
            dockerfile: Dockerfile
        image: ahmadseptian/laravel-backend:latest
        env_file:
            - ./.env.laravel
        volumes:
            - .:/var/www

    backend-server:
        <<: *backendbase
        platform: linux/x86_64
        depends_on:
            - mysql
        restart: always
        entrypoint: ["sh", "-c", "php artisan serve --host=0.0.0.0 --port=9000"]

    db-migrate:
        <<: *backendbase
        platform: linux/x86_64
        depends_on:
            - mysql
        entrypoint: ["sh", "-c", "php artisan migrate"]

    db-seed:
        <<: *backendbase
        platform: linux/x86_64
        depends_on:
            - mysql
        entrypoint: ["sh", "-c", "php artisan db:seed"]

    nginx:
        image: nginx:stable-alpine
        container_name: webserver
        restart: unless-stopped
        depends_on:
            - backend-server
        ports:
            - 8081:80
        volumes:
            - .:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf

volumes:
    mysqldata:
        external: true
